### ISSUE TITLE
Error Uncaught in Promise when JSPrintManager is not installed (V4)

### ISSUE THREAD

**Issue by go2theG** [neodynamic/JSPrintManager#39]
When JSPrintManager Client App V4 is not installed on the computer, there is the following error in the console log:
`WebSocket connection to 'wss://localhost:24443/' failed:`

This exception is expected and was also there in V3.

But in V4 there is another Exception that shows up.

`Error: Uncaught (in promise): Event: {"isTrusted":true}
    at resolvePromise (zone-evergreen.js:798:1)
    at zone-evergreen.js:705:1
    at i (JSPrintManager.js:2:31492)
    at ZoneDelegate.invoke (zone-evergreen.js:364:1)
    at Object.onInvoke (core.js:27504:1)
    at ZoneDelegate.invoke (zone-evergreen.js:363:1)
    at Zone.run (zone-evergreen.js:123:1)
    at zone-evergreen.js:857:1
    at ZoneDelegate.invokeTask (zone-evergreen.js:399:1)
    at Object.onInvokeTask (core.js:27492:1)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398:1)
    at Zone.runTask (zone-evergreen.js:167:1)
    at drainMicroTaskQueue (zone-evergreen.js:569:1)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:484:1)
    at invokeTask (zone-evergreen.js:1621:1)
    at WebSocket.globalZoneAwareCallback (zone-evergreen.js:1647:1)`

I think the behaviour with V3 (no exception) was better. Or is there a way to prevent this error. I see on your demo page it's just a warning.

**Comment by go2theG** [comment]
I only realized now, that the port has chaned from 23443 to 24443 in V4. WIth that knowladge, one can filter the Exception in an Angular ErrorHandler.
