### ISSUE TITLE
JSPrintManager 6.0.3 with NextJS 14.1.4

### ISSUE THREAD

**Issue by ViniciusFuhrBorba** [neodynamic/JSPrintManager#65]
I'm trying to use the JSPrintManager dependency on version 6.0.3 with NextJS on version 14.1.4 and when I start the application I'm getting the following error:

```
⨯ node_modules\jsprintmanager\JSPrintManager.js (2:45615) @ 9../Enums
 ⨯ ReferenceError: document is not defined
    at __webpack_require__ (C:\Users\Borba\Desktop\teste\.next\server\webpack-runtime.js:33:42)
    at eval (./src/app/page.tsx:7:72)
    at (ssr)/./src/app/page.tsx (C:\Users\Borba\Desktop\teste\.next\server\app\page.js:180:1)
    at __webpack_require__ (C:\Users\Borba\Desktop\teste\.next\server\webpack-runtime.js:33:42)
    at JSON.parse (<anonymous>)
```
    
My page.tsx is: 

```
"use client";

import { JSPrintManager, WSStatus } from "jsprintmanager";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    JSPrintManager.auto_reconnect = false;
    JSPrintManager.start(false);
    if (handleJSPMStatus()) {
      JSPrintManager.getScanners().then(function (scannersList) {
        for (var i = 0; i < scannersList.length; i++) {
          console.log(scannersList[i]);
        }
      });
    }
  }, []);

  function handleScanner() {}

  function handleJSPMStatus() {
    if (JSPrintManager.websocket_status == WSStatus.Open) {
      return true;
    }
    if (JSPrintManager.websocket_status == WSStatus.Closed) {
      return false;
    }
    if (JSPrintManager.websocket_status == WSStatus.Blocked) {
      return false;
    }
  }

  return <button onClick={() => handleScanner()}>start scanning</button>;
}
```

How can I solve this probleme?

**Comment by imbhargav5** [comment]
I believe this should component should be run using next/dynamic with ssr: false.
